[frontends.frontend__2F]
backend = "backend__2F"
passHostHeader = true

[backends.backend__2F.servers.server1]
url = "http://127.0.0.1:8081"
weight = 1

[frontends.frontend__2F.routes.test]
rule = "PathPrefix:/"
data = "{\"hub\": true}"
