# the default entrypoint
defaultentrypoints = ["http"]

# the api entrypoint
[api]
dashboard = true
entrypoint = "auth_api"

# websockets protocol
[wss]
protocol = "http"

# the port on localhost where traefik accepts http requests
[entryPoints.http]
address = ":8000"

# the port on localhost where the traefik api and dashboard can be found
[entryPoints.auth_api]
address = ":8099"

# authenticate the traefik api entrypoint
[entryPoints.auth_api.auth.basic]
users = [ "admin:$apr1$kRsae0RF$9lut4Yc6NAypI80j9DNUX/",]

# the dynamic configuration file
[file]
filename = "rules.toml"
watch = true
