debug = true

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/letsencrypt/cr/0000_csr-certbot.pem"
      keyFile = "/etc/letsencrypt/keys/0000_key-certbot.pem"

[docker]
domain = "docker.local"
watch = true

[api]
  [api.statistics]
    recentErrors = 10
